### ISSUE TITLE
python 版本

### ISSUE THREAD

**Issue by SiYuetian-uvu** [xuanyuzhang21/EditGuard#9]
您好，请问一下你们运行的python版本是多少呢

**Comment by super-danny** [comment]
Seems that python3.10 is the one that runs. But I'm having a lot of issues with the pip modules, I had to manually install specific versions of them.

Right now I'm attempting to train this model with no success.

**Comment by user172894254** [comment]
@SiYuetian-uvu Hello, is your problem solved? I'm trying to reproduce the code and I find that the dependencies can't be installed properly, is that the same for your problem?

**Comment by xuanyuzhang21** [comment]
The python version we use is 3.10. Please relax some dependencies if you encounter pip installation problems. In fact, only some key packages are necessary, such as basicsr, opencv-python, einops, and so on.
